# ベースイメージの選択
FROM nginx/unit:1.14.0-python3.7

# アップデート＆pipインストール
RUN apt update -y
RUN apt install -y python3-pip
# pythonモジュールのインストール
RUN pip3 install Flask
RUN pip3 install pymysql
RUN pip3 install cryptography
# ↑　パスワード認証に必要